on:
  push:
    branches:
      - master
    paths:
    - 'sanity/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity Application
    steps:
    - uses: actions/checkout@master
    - name: NPM install
      run: "npm install"
      working-directory: 'sanity'
    - name: Build app
      run: "./node_modules/.bin/sanity build"
      env:
        SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
      working-directory: 'sanity'
    - name: Deploy app
      run: "./node_modules/.bin/sanity deploy"
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      working-directory: 'sanity'
    - name: Deploy GraphQL API
      run: "./node_modules/.bin/sanity graphql deploy"
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      working-directory: 'sanity'
