on:
  push:
    branches:
      - master
    paths:
    - 'sanity/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity Application
    steps:
    - uses: actions/checkout@master
    - name: NPM install
      run: "npm install"
      working-directory: 'sanity'
    - name: Build app
      run: "npx sanity build"
      env:
        SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
      working-directory: 'sanity'
    - name: Deploy app
      run: "npx sanity deploy"
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      working-directory: 'sanity'
    - name: Deploy GraphQL API
      run: "npx sanity graphql deploy"
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      working-directory: 'sanity'
